import type { Sandbox } from "@cloudflare/sandbox";

import type { Artifacts } from "./artifacts.ts";

// The Worker environment: bindings + secrets. In a real deploy this is generated by
// `wrangler types` from wrangler.jsonc; we declare it by hand for the MVP. Secrets are
// plain `env.*` values set with `wrangler secret put` — there is no separate vault.
//
// Convention: each workflow gets a Workflow binding named UPPER_SNAKE(workflow.name)
// (see bindingName() in workflow.ts), so "linear-to-pr" -> env.LINEAR_TO_PR.
export interface Env {
  // Workflow bindings (durable execution engine — one per workflow).
  readonly LINEAR_TO_PR: Workflow;

  // Container/Durable Object that backs the coding sandbox.
  readonly Sandbox: DurableObjectNamespace<Sandbox>;
  // R2 bucket the Sandbox SDK uses for createBackup/restoreBackup.
  readonly BACKUP_BUCKET: R2Bucket;
  // Cloudflare Artifacts — where the working repo (the "artifact") lives.
  readonly ARTIFACTS: Artifacts;

  // Secrets.
  readonly GITHUB_TOKEN: string;
  readonly ANTHROPIC_API_KEY: string;
  readonly LINEAR_TOKEN: string;
  readonly LINEAR_SIGNING_SECRET: string;
}
